### ISSUE TITLE
Error: Validation failed for the the 'os' entry options (RuntimeError)

### ISSUE THREAD

**Issue by cmonty14** [fdupoux/rubackup#4]
Hi,
I'm running into this error when executing rubackup:
```
vllspdevsles12:~ # /opt/rubackup/rubackup.rb --logfile /var/log/rubackup/rubackup.dbg --loglevel 4 --outlevel 3 >> /var/log/rubackup/rubackup.log
/opt/rubackup/lib/core/config.rb:285:in `block (2 levels) in validate_config': Validation failed for the the 'os' entry options (RuntimeError)
        from /opt/rubackup/lib/core/config.rb:261:in `each'
        from /opt/rubackup/lib/core/config.rb:261:in `block in validate_config'
        from /opt/rubackup/lib/core/config.rb:251:in `each'
        from /opt/rubackup/lib/core/config.rb:251:in `validate_config'
        from /opt/rubackup/rubackup.rb:132:in `<main>
```

The error message indicates an issue related to _/etc/rubackup.d/03-sles12sp3.yaml_:
```
---
entries:
    os:
        enabled: true
        backup_type: ModuleBackupFsarchiver
        backup_schedule: long_term
        backup_opts:
            description: 'Consistent backup of vllspdevsles12 root file system and var directory'
            excludes:
                - '/backup/*'
                - '/backup_rbd_lve/*'
                - '/lost+found/*'
                - '/media/*'
                - '/mnt/*'
                - '/net/*'
                - '/sapmnt/*'
                - '/tmp/*'
                - '/var/tmp/*'
            command_opts:
                - '-Z15'
                - '-j4'
            filesystems:
                - block_device: /dev/sda1
                - block_device: /dev/vg_sys_r1/root
                  snapshot_type: lvm
                  snapshot_size: 12288M
                - block_device: /dev/vg_sys_r1/var
                  snapshot_type: lvm
                  snapshot_size: 4096M
        bakfile_dir: /backup_rbd_lve/
        bakfile_owner: root
        bakfile_group: root
        bakfile_mode: 0600
        bakfile_basename: bkp_vllspdevsles12
```
Can you please advise to fix this issue?

THX
